[package]
name = "code"
version = "0.1.0"
authors = ["Arlie Davis <arlie.davis@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
log = "0.4.*"
env_logger = "0.6"
lazy_static = "1.3"
